from pydantic import BaseModel

class PropostaData(BaseModel):
    proposta: str = ""
    aleta: str = ""
    diametro_aleta: str = ""
    espacamento: str = ""
    diametro_corpo: str = ""
    aisi: str = ""
    espessura: str = ""
    furo: str = ""
    haste: str = ""
    diametro: str = ""
    preco_unitario: str = ""
    preco_lote: str = ""
    frete_pac: str = ""
    frete_sedex: str = ""
    condiçao_envio: str = ""
    data: str = ""
    nome_vendedor: str = ""
    email_vendedor: str = ""